spring:
  application:
    name: consumer
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
  kafka:
    bootstrap-servers: ${KAFKA_SERVER}
    consumer:
      group-id: consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        spring:
          json:
            type:
              mapping: message:com.github.aliakseisilivonchyk.consumer.dto.MessageDto

com:
  github:
    aliakseisilivonchyk:
      kafka:
        request-topic: ${KAFKA_REQUEST_TOPIC}