spring:
  application:
    name: producer
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
  kafka:
    bootstrap-servers: ${KAFKA_SERVER}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
      properties:
        spring:
          json:
            type:
              mapping: message:com.github.aliakseisilivonchyk.producer.dto.MessageDto
    consumer:
      group-id: producer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

com:
  github:
    aliakseisilivonchyk:
      kafka:
        request-topic: ${KAFKA_REQUEST_TOPIC}
        reply-topic: ${KAFKA_REPLY_TOPIC}
        message-type: ${KAFKA_MESSAGE_TYPE}
        message-rate: ${KAFKA_MESSAGE_RATE}
        producer-id: ${KAFKA_PRODUCER_ID}